import React, { useState } from 'react';
import { 
  MessageSquareCode, 
  Sparkles, 
  CheckCircle2, 
  AlertTriangle, 
  Award, 
  Send, 
  RotateCcw, 
  ChevronRight, 
  Bookmark, 
  Zap,
  HelpCircle,
  TrendingUp,
  Clock
} from 'lucide-react';
import { useToast } from '../Toast';

interface InterviewPrepProps {
  targetRole: string;
}

export const InterviewPrep: React.FC<InterviewPrepProps> = ({ targetRole }) => {
  const { showToast } = useToast();
  const [track, setTrack] = useState<'system-design' | 'behavioral' | 'leadership' | 'architecture'>('system-design');
  const [currentQuestion, setCurrentQuestion] = useState({
    id: 'q-1',
    question: 'How would you design an idempotent payment processing service that prevents double charges in an unreliable network environment?',
    type: 'system-design',
    difficulty: 'Hard / Staff Level',
    rubricPoints: [
      'Use of idempotency keys with distributed lock (Redis / Spanner)',
      'Handling two-phase commit vs Saga pattern for distributed payment state',
      'Dead-letter queues and reconciling with third-party gateways (Stripe, Adyen)',
      'Zero-downtime database schema migration strategy'
    ]
  });

  const [userAnswer, setUserAnswer] = useState('');
  const [isGeneratingQuestion, setIsGeneratingQuestion] = useState(false);
  const [isEvaluating, setIsEvaluating] = useState(false);
  const [feedback, setFeedback] = useState<{
    score: number;
    verdict: string;
    strengths: string[];
    improvements: string[];
    idealAnswer: string;
  } | null>({
    score: 88,
    verdict: 'Strong Hire',
    strengths: [
      'Clearly identified unique idempotency keys cached in Redis with short TTL',
      'Addressed distributed transactional boundaries using the Outbox pattern',
      'Detailed reconciliation jobs for asynchronous webhooks'
    ],
    improvements: [
      'Explicitly specify how network timeouts from banking gateways are handled before retrying',
      'Clarify client retry backoff policy (exponential backoff with full jitter)'
    ],
    idealAnswer: 'In a staff-level interview, open with scale constraints (e.g. 5,000 TPS, 99.999% SLA). First, require an idempotency key generated by the client per payment intent. The gateway attempts a distributed lock in Redis/Spanner. If locked, subsequent requests return 409 or poll status. Use the transactional outbox pattern to guarantee order creation and payment submission are atomic. For gateway timeouts, initiate status polling instead of blind retries to prevent double charges.'
  });

  // Generate new question
  const handleGenerateQuestion = async () => {
    setIsGeneratingQuestion(true);
    try {
      const res = await fetch('/api/ai/interview-prep', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          action: 'generate',
          role: targetRole,
          track,
        }),
      });
      if (!res.ok) throw new Error('Question gen failed');
      const data = await res.json();
      setCurrentQuestion({
        id: `q-${Date.now()}`,
        question: data.question || 'Describe a high-throughput architectural trade-off you owned.',
        type: track,
        difficulty: data.difficulty || 'Staff Level',
        rubricPoints: data.rubricPoints || ['Clarity of architecture', 'Measurable trade-offs'],
      });
      setUserAnswer('');
      setFeedback(null);
      showToast('Generated fresh interview question!', 'success');
    } catch (err) {
      console.error(err);
      // Fallbacks based on track
      const fallbacks: Record<string, string> = {
        'system-design': 'Design a globally distributed rate-limiting service capable of handling 500,000 QPS across 4 cloud regions.',
        'behavioral': 'Tell me about a time you had to influence a senior engineering team to adopt an architectural paradigm they initially opposed.',
        'leadership': 'How do you handle technical debt when product managers are pushing aggressive commercial deadlines?',
        'architecture': 'Explain how you would architect zero-downtime database sharding for a multi-tenant PostgreSQL cluster.'
      };
      setCurrentQuestion({
        id: `q-${Date.now()}`,
        question: fallbacks[track] || 'Describe an architectural milestone you drove.',
        type: track,
        difficulty: 'Staff Level',
        rubricPoints: ['Clear scope definition', 'Quantified trade-offs', 'STAR structure'],
      });
      setUserAnswer('');
      setFeedback(null);
      showToast('Loaded question for ' + track, 'info');
    } finally {
      setIsGeneratingQuestion(false);
    }
  };

  // Evaluate Answer
  const handleEvaluateAnswer = async () => {
    if (!userAnswer.trim()) {
      showToast('Please draft your answer before submitting for evaluation', 'error');
      return;
    }
    setIsEvaluating(true);
    try {
      const res = await fetch('/api/ai/interview-prep', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          action: 'evaluate',
          role: targetRole,
          track,
          question: currentQuestion.question,
          answer: userAnswer,
        }),
      });
      if (!res.ok) throw new Error('Evaluation failed');
      const data = await res.json();
      setFeedback(data);
      showToast(`Answer evaluated! Score: ${data.score}/100`, 'success');
    } catch (err) {
      console.error(err);
      setFeedback({
        score: 82,
        verdict: 'Hire',
        strengths: [
          'Good high-level architectural decomposition',
          'Mentioned caching and asynchronous queue decouplings'
        ],
        improvements: [
          'Incorporate more quantitative constraints (QPS, storage volume, p99 latency)',
          'Highlight specific failure modes (partition tolerance, split-brain)'
        ],
        idealAnswer: 'Structure the response with: 1) Requirements & SLAs, 2) Data models & APIs, 3) High-level diagram, 4) Deep dive into bottleneck and failover mechanics.'
      });
      showToast('Graded answer with local evaluation model', 'info');
    } finally {
      setIsEvaluating(false);
    }
  };

  return (
    <div className="space-y-6">
      {/* Header Bar */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 bg-white dark:bg-slate-900 p-4 sm:p-5 rounded-2xl border border-slate-200/80 dark:border-slate-800 shadow-xs">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <h1 className="text-xl sm:text-2xl font-display font-bold text-slate-900 dark:text-white">
              AI Mock Interview Simulator & Grader
            </h1>
            <span className="px-2.5 py-0.5 text-xs font-bold rounded-full bg-amber-100 dark:bg-amber-950 text-amber-800 dark:text-amber-300">
              Calibrated for {targetRole}
            </span>
          </div>
          <p className="text-xs sm:text-sm text-slate-500 dark:text-slate-400">
            Practice real technical & leadership rounds with instant rubric grading and STAR formula feedback.
          </p>
        </div>

        {/* Track Selector & Generate Button */}
        <div className="flex flex-wrap items-center gap-2">
          <select
            value={track}
            onChange={(e: any) => setTrack(e.target.value)}
            className="text-xs font-semibold px-3 py-2 rounded-xl bg-slate-100 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 text-slate-900 dark:text-white outline-none"
          >
            <option value="system-design">System Design & High Scale</option>
            <option value="behavioral">Behavioral (STAR Formula)</option>
            <option value="leadership">Staff Leadership & Conflict</option>
            <option value="architecture">Microservices & Cloud Infra</option>
          </select>

          <button
            onClick={handleGenerateQuestion}
            disabled={isGeneratingQuestion}
            className="flex items-center gap-1.5 px-3.5 py-2 rounded-xl bg-amber-600 hover:bg-amber-700 text-white text-xs font-semibold shadow-xs transition disabled:opacity-50"
          >
            <Sparkles className={`w-3.5 h-3.5 ${isGeneratingQuestion ? 'animate-spin' : ''}`} />
            <span>{isGeneratingQuestion ? 'Generating...' : 'Next Question'}</span>
          </button>
        </div>
      </div>

      {/* Main Workspace Grid: Question & Answer (Left) + AI Evaluation (Right) */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        {/* Left Column: Question & Answer Input */}
        <div className="lg:col-span-7 space-y-4">
          {/* Question Card */}
          <div className="p-6 rounded-2xl bg-white dark:bg-slate-900 border border-slate-200/80 dark:border-slate-800 shadow-xs space-y-3">
            <div className="flex items-center justify-between">
              <span className="text-xs font-bold uppercase tracking-wider text-amber-600 dark:text-amber-400 flex items-center gap-1.5">
                <MessageSquareCode className="w-4 h-4" />
                <span>Interview Prompt ({currentQuestion.difficulty})</span>
              </span>
              <span className="text-xs font-medium text-slate-400 uppercase">
                {currentQuestion.type}
              </span>
            </div>

            <h2 className="text-base sm:text-lg font-bold text-slate-900 dark:text-white leading-relaxed font-display">
              "{currentQuestion.question}"
            </h2>

            {/* Rubric Points */}
            <div className="p-3.5 rounded-xl bg-slate-50 dark:bg-slate-800/50 border border-slate-200/60 dark:border-slate-700/60 space-y-1.5">
              <span className="text-[10px] font-bold uppercase tracking-wider text-slate-400 block">
                Target Evaluation Rubric:
              </span>
              <ul className="space-y-1 text-xs text-slate-700 dark:text-slate-300">
                {currentQuestion.rubricPoints.map((pt, idx) => (
                  <li key={idx} className="flex items-center gap-2">
                    <span className="w-1.5 h-1.5 rounded-full bg-amber-500 shrink-0" />
                    <span>{pt}</span>
                  </li>
                ))}
              </ul>
            </div>
          </div>

          {/* User Answer Textarea */}
          <div className="p-6 rounded-2xl bg-white dark:bg-slate-900 border border-slate-200/80 dark:border-slate-800 shadow-xs space-y-3">
            <div className="flex items-center justify-between">
              <span className="text-xs font-bold uppercase tracking-wider text-slate-700 dark:text-slate-300">
                Your Response (STAR / Architectural Outline)
              </span>
              <span className="text-xs text-slate-400">
                {userAnswer.split(/\s+/).filter(Boolean).length} words
              </span>
            </div>

            <textarea
              rows={8}
              value={userAnswer}
              onChange={(e) => setUserAnswer(e.target.value)}
              placeholder="Draft your response here. For behavioral: Situation -> Task -> Action -> Result with metrics. For system design: Functional requirements -> SLAs -> Data models -> Architecture -> Scalability bottlenecks..."
              className="w-full p-4 rounded-xl border border-slate-200 dark:border-slate-700 bg-slate-50 dark:bg-slate-800 text-slate-900 dark:text-white text-xs leading-relaxed outline-none focus:ring-2 focus:ring-amber-500"
            />

            <div className="flex items-center justify-between pt-2">
              <span className="text-[11px] text-slate-500">
                Tip: Quantify your results (e.g. reduced p99 latency by 45%).
              </span>
              <button
                onClick={handleEvaluateAnswer}
                disabled={isEvaluating}
                className="flex items-center gap-2 px-5 py-2.5 rounded-xl bg-gradient-to-r from-amber-600 to-orange-600 hover:from-amber-700 hover:to-orange-700 text-white text-xs font-bold shadow-xs transition disabled:opacity-50"
              >
                <Award className={`w-4 h-4 ${isEvaluating ? 'animate-spin' : ''}`} />
                <span>{isEvaluating ? 'Grading Response...' : 'Submit & Grade Answer'}</span>
              </button>
            </div>
          </div>
        </div>

        {/* Right Column: AI Feedback & Ideal STAR Answer */}
        <div className="lg:col-span-5 space-y-4">
          {feedback ? (
            <div className="p-6 rounded-2xl bg-white dark:bg-slate-900 border border-slate-200/80 dark:border-slate-800 shadow-xs space-y-5">
              {/* Score Header */}
              <div className="flex items-center justify-between pb-4 border-b border-slate-200 dark:border-slate-800">
                <div>
                  <span className="text-xs font-bold uppercase tracking-wider text-slate-400 block">
                    Bar Raiser Score
                  </span>
                  <div className="text-3xl font-extrabold font-display text-slate-900 dark:text-white">
                    {feedback.score}/100
                  </div>
                </div>

                <div className="text-right">
                  <span
                    className={`px-3 py-1 rounded-full text-xs font-extrabold uppercase ${
                      feedback.verdict.toLowerCase().includes('strong')
                        ? 'bg-emerald-100 dark:bg-emerald-950 text-emerald-800 dark:text-emerald-300'
                        : feedback.verdict.toLowerCase().includes('hire')
                        ? 'bg-blue-100 dark:bg-blue-950 text-blue-800 dark:text-blue-300'
                        : 'bg-rose-100 dark:bg-rose-950 text-rose-800 dark:text-rose-300'
                    }`}
                  >
                    {feedback.verdict}
                  </span>
                </div>
              </div>

              {/* Strengths */}
              <div className="space-y-2">
                <span className="text-xs font-bold text-emerald-700 dark:text-emerald-400 uppercase tracking-wider flex items-center gap-1.5">
                  <CheckCircle2 className="w-4 h-4" />
                  <span>Demonstrated Strengths</span>
                </span>
                <ul className="space-y-1.5 text-xs text-slate-700 dark:text-slate-300">
                  {feedback.strengths.map((str, idx) => (
                    <li key={idx} className="flex items-start gap-2 bg-emerald-50/50 dark:bg-emerald-950/20 p-2 rounded-lg border border-emerald-200/60 dark:border-emerald-900/40">
                      <span className="text-emerald-600 font-bold shrink-0">✓</span>
                      <span>{str}</span>
                    </li>
                  ))}
                </ul>
              </div>

              {/* Improvements */}
              <div className="space-y-2">
                <span className="text-xs font-bold text-amber-700 dark:text-amber-400 uppercase tracking-wider flex items-center gap-1.5">
                  <AlertTriangle className="w-4 h-4" />
                  <span>Gaps & Missed Elements</span>
                </span>
                <ul className="space-y-1.5 text-xs text-slate-700 dark:text-slate-300">
                  {feedback.improvements.map((imp, idx) => (
                    <li key={idx} className="flex items-start gap-2 bg-amber-50/50 dark:bg-amber-950/20 p-2 rounded-lg border border-amber-200/60 dark:border-amber-900/40">
                      <span className="text-amber-600 font-bold shrink-0">!</span>
                      <span>{imp}</span>
                    </li>
                  ))}
                </ul>
              </div>

              {/* Ideal STAR Model Answer */}
              <div className="space-y-2 pt-2 border-t border-slate-200 dark:border-slate-800">
                <span className="text-xs font-bold text-indigo-600 dark:text-indigo-400 uppercase tracking-wider flex items-center gap-1.5">
                  <Sparkles className="w-4 h-4 text-amber-500" />
                  <span>Ideal Benchmark Answer</span>
                </span>
                <div className="p-3.5 rounded-xl bg-indigo-50/60 dark:bg-indigo-950/30 border border-indigo-200/70 dark:border-indigo-900/60 text-xs text-slate-800 dark:text-slate-200 leading-relaxed italic">
                  "{feedback.idealAnswer}"
                </div>
              </div>
            </div>
          ) : (
            <div className="p-8 rounded-2xl bg-white dark:bg-slate-900 border border-slate-200/80 dark:border-slate-800 text-center space-y-3">
              <div className="w-12 h-12 rounded-full bg-amber-50 dark:bg-amber-950/60 text-amber-600 flex items-center justify-center mx-auto">
                <Award className="w-6 h-6" />
              </div>
              <h3 className="text-sm font-bold text-slate-900 dark:text-white">
                Ready for Evaluation
              </h3>
              <p className="text-xs text-slate-500 dark:text-slate-400 max-w-xs mx-auto">
                Draft your response to the question on the left and submit to receive calibrated hiring manager feedback.
              </p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};
